version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: vatboxltd/vatbox-build-primary
    environment:
      SBT_VERSION: 1.1.6
      SBT_OPTS: "-Xms512M -Xmx1536M -Xss1M"

    steps:
      - checkout

      - restore_cache:
          keys:
            - buckazoid-{{ checksum "build.sbt" }}-{{ checksum "project/Dependencies.scala" }}
            - buckazoid-

      - run:
          name: sbt update
          command: sbt update dumpLicenseReport

      - run:
          name: Test
          command:  sbt coverage test

      - run:
          name: Coverage Report
          command:  sbt coverageReport

      - store_test_results:
          path: target/test-reports

      - store_artifacts:
          path: target/license-reports
          destination: license-reports

      - store_artifacts:
          path: target/scala-2.12/scoverage-report
          destination: scoverage-report

      - run:
          name: Build
          command: sbt clean +compile

      - save_cache:
          key: buckazoid-{{ checksum "build.sbt" }}-{{ checksum "project/Dependencies.scala" }}
          paths:
            - ~/.m2
            - ~/.sbt
            - ~/.ivy2

      - deploy:
          name: Publish
          requires:
            - Build
          filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
          command: sbt +publish
